Analysing the sales data of the last 12 months for the company RetailEdge

Loading and understanding the data

In [3]:
import pandas as pd
import os

In [8]:
filename = "sales_data.csv"

sales_data = pd.read_csv(filename)
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      5000 non-null   str
 1   order_date    5000 non-null   str
 2   customer_id   5000 non-null   str
 3   region        4980 non-null   str
 4   category      5000 non-null   str
 5   product_name  5000 non-null   str
 6   quantity      5000 non-null   int64
 7   unit_price    5000 non-null   float64
 8   discount      4980 non-null   float64
 9   revenue       5000 non-null   float64
 10  returned      5000 non-null   bool
dtypes: bool(1), float64(3), int64(1), str(6)
memory usage: 395.6 KB

In [10]:
sales_data.head(10)

,order_id,order_date,customer_id,region,category,product_name,quantity,unit_price,discount,revenue,returned
0,ORD-13406,2024-11-28,CUST-3898,South,Electronics,Laptop Stand,1,49.99,0.00,49.99,False
1,ORD-10757,2024-07-09,CUST-2356,East,Electronics,Webcam HD,1,79.99,0.05,75.99,False
2,ORD-13624,2024-04-26,CUST-4919,North,Electronics,Webcam HD,3,79.99,0.00,239.97,False
3,ORD-14544,2024-05-01,CUST-1906,South,Home & Garden,Scented Candles,1,19.99,0.05,18.99,True
4,ORD-13235,2024-03-21,CUST-4518,West,Clothing,Wool Sweater,2,79.99,0.15,135.98,False
5,ORD-11868,2024-02-18,CUST-4933,East,Electronics,Laptop Stand,4,49.99,0.15,169.97,False
6,ORD-12916,2024-10-07,CUST-1446,South,Clothing,Yoga Pants,1,44.99,0.05,42.74,False
7,ORD-13335,2024-10-02,CUST-1394,North,Electronics,USB-C Hub,1,39.99,0.00,39.99,False
8,ORD-13527,2024-10-07,CUST-4738,North,Clothing,Rain Coat,2,119.99,0.10,215.98,False
9,ORD-12827,2024-02-25,CUST-4903,North,Home & Garden,Coffee Maker,2,69.99,0.00,139.98,False

In [11]:
sales_data.sample(10)

,order_id,order_date,customer_id,region,category,product_name,quantity,unit_price,discount,revenue,returned
834,ORD-11222,2024-06-15,CUST-2155,South,Home & Garden,LED Desk Lamp,1,44.99,0.00,44.99,True
402,ORD-11434,2024-02-12,CUST-4926,East,Clothing,Rain Coat,2,119.99,0.00,239.98,False
662,ORD-12015,2024-06-08,CUST-4631,South,Clothing,Casual Sneakers,2,89.99,0.10,161.98,False
4200,ORD-10534,2024-11-13,CUST-2104,South,Electronics,Mechanical Keyboard,1,129.99,0.05,123.49,False
3199,ORD-13214,2024-03-23,CUST-4285,North,Clothing,Cotton T-Shirt,2,24.99,0.25,37.48,False
2402,ORD-11786,2024-09-15,CUST-3683,North,Clothing,Wool Sweater,1,79.99,0.15,67.99,True
3753,ORD-10953,2024-12-06,CUST-1598,East,Home & Garden,Air Purifier,1,159.99,0.00,159.99,False
4302,ORD-14234,2024-01-04,CUST-4084,South,Home & Garden,Storage Organizer,2,29.99,0.10,53.98,True
2573,ORD-11541,2024-02-26,CUST-1857,North,Electronics,Laptop Stand,5,49.99,0.00,249.95,False
3875,ORD-14409,2024-07-08,CUST-2919,West,Home & Garden,Air Purifier,1,159.99,0.10,143.99,False

In [31]:
sales_data.sample().isnull()

,order_id,order_date,customer_id,region,category,product_name,quantity,unit_price,discount,revenue,returned
754,False,False,False,False,False,False,False,False,False,False,False